### ISSUE TITLE
Volume scroll: Only when a hotkey is held

### ISSUE THREAD

**Issue by ArchiveAnon** [VampireChicken12/youtube-enhancer#104]
Thank you for this extension and carrying on some useful features I really loved. I was wondering if it would be possible to implement a feature/option that only changed volume when scrolling if right click (or any hotkey really) was held down while scrolling. I find myself often accidentally changing volume without this and it would be a nice-to-have thing. 

Thanks again for the effort, its greatly appreciated.

**Comment by VampireChicken12** [comment]
@ArchiveAnon that should be possible. Right now I'm working on improving some of the code. I'm also making tests for the code to make sure everything is working before releasing the next version.

**Comment by VampireChicken12** [comment]
@ArchiveAnon would the alt or ctrl key work? if I want to get this new feature out fast those two would be the easiest otherwise it will take a bit longer.

**Comment by ArchiveAnon** [comment]
Honestly, any key works. Just can be a bit of an annoyance if you scroll and accidentally mute the video you're watching or blast the volume haha. Thanks for taking the time to do this!

**Comment by VampireChicken12** [comment]
Alright, the easiest way for me to add this feature is "ctrl", "alt" or "shift" key press. Because in the event for the scroll wheel there are properties that tell if those keys are pressed when scrolling.

https://github.com/VampireChicken12/youtube-enhancer/blob/dev/src/features/scrollWheelVolumeControl/index.ts#L30

**Comment by VampireChicken12** [comment]
Although I can do it the harder way which will allow for a wider range of keys to choose from. 

https://keyjs.dev/#keycodes-table

**Comment by VampireChicken12** [comment]
If you have Discord feel free to add me to talk about this new feature and other features. vampirechicken is my Discord username

**Comment by VampireChicken12** [comment]
I decided that the following keys will be alright 

Alt key, Ctrl key, Shift key

**Comment by VampireChicken12** [comment]
@ArchiveAnon version 1.12.0 includes "Scroll wheel volume control modifier key feature" 
![YouTube_Enhancer__Options_-_Google_Chrome_e4DxUokOsx](https://github.com/VampireChicken12/youtube-enhancer/assets/45531575/1400521f-a08d-4c46-8d35-baa73ec80208)
