### ISSUE TITLE
Adblocker .. block all video

### ISSUE THREAD

**Issue by Foul-Tarnished** [VampireChicken12/youtube-enhancer#143]
Please remove the built-in adblocker, it's broken/outdated.

Everyone uses UBlock Origin or other extensions that are specificaly made to block ads, and get updated to keep working.

I cannot play any video with this extension, even if I have UBlock Origin.
I need to manually disable your adblocker in the extension setting.

Either make it disabled by default, and says that it's way less robust than other ads blocker
Or just remove that feature.

**Comment by VampireChicken12** [comment]
This extension does not contain an adblocker

**Comment by VampireChicken12** [comment]
@Foul-Tarnished I forgot to mention before. The extension has no code for adblocking please remove your review on Mozilla addons.

**Comment by benji78** [comment]
@Foul-Tarnished You likely ended up on the wrong Firefox extension's page, just like I did to report the exact same issue.
The dev of _Enhancer for YouTube™_ posted a note one his website :

> Distribution of Enhancer for YouTube™ temporarily stopped!
> Due to the countless changes that the YouTube developers have made, Enhancer for YouTube™ is now completely broken for Firefox (partially works for Chromium based browsers) so I had to pause its distribution. A huge amount of work is necessary to fix all the issues so don't expect a new version to be released in the upcoming days. Please do not contact me for an estimated date of release, I don't have one.

[mrfdev.com/how-to-use-enhancer-for-youtube](https://www.mrfdev.com/how-to-use-enhancer-for-youtube)

**Comment by VampireChicken12** [comment]
@benji78 thank you for the clarification.
