### ISSUE TITLE
Feature Request: Add Open Transcript button in Feature Menu

### ISSUE THREAD

**Issue by lamyergeier** [VampireChicken12/youtube-enhancer#164]
Recently Youtube has shifted the "Open Transcript" button from the "3 dots menu" below the player to in the bottom of description. Now we have to scroll and search for this "Open Transcript" button.

Could you please add "Open Transcript" button  in the Feature Menu in the player?

**Comment by VampireChicken12** [comment]
@lamyergeier Let me look into it and I'll get back to you.

**Comment by VampireChicken12** [comment]
@lamyergeier The feature is done being coded it will be available in the next release. I still have a couple things to finish up before then.

**Comment by VampireChicken12** [comment]
@lamyergeier the feature is available now

**Comment by VampireChicken12** [comment]
@all-contributors please add @lamyergeier for ideas

**Comment by lamyergeier** [comment]
@VampireChicken12 I am using [v1.17.1](https://github.com/VampireChicken12/youtube-enhancer/releases/tag/v1.17.1). But I don't see the show transcript, as can be seen below:

![image](https://github.com/VampireChicken12/youtube-enhancer/assets/42092626/2a9deb1f-ef87-4512-820b-f97831693cbf)

**Comment by VampireChicken12** [comment]
@lamyergeier is the option enabled in the settings and does that video actually have a transcript? The button only appears when the video has a transcript

**Comment by VampireChicken12** [comment]
I just tested with the same video, it does have one but the button didn't appear let me look into the code and figure out what is going wrong that the button isn't appearing
