### ISSUE TITLE
[translation request] Traditional Chinese

### ISSUE THREAD

**Issue by SleepyPrince** [VampireChicken12/youtube-enhancer#170]
Request to add Traditional Chinese in crowdin

**Comment by VampireChicken12** [comment]
@SleepyPrince Traditional Chinese has been added to the crowdin

**Comment by VampireChicken12** [comment]
@all-contributors add @SleepyPrince for translations

**Comment by VampireChicken12** [comment]
@SleepyPrince thanks for your translations they are available in version 1.17.3 of the extension
