### ISSUE TITLE
Descriptions on shorts not showing anymore

### ISSUE THREAD

**Issue by DesmoGiec** [VampireChicken12/youtube-enhancer#208]
**Describe the bug**
Since some days I can't see descriptions on shorts anymore.

Descriptions and channel will show up just for milliseconds, then disappear when the icon of the channel loads up in the bottom right corner next to the video
Disabling yt enhancer solve the issue.

**To Reproduce**

1. Open a short.

https://github.com/VampireChicken12/youtube-enhancer/assets/114442648/d8bec48f-4780-4a09-9bc6-103a3c7ed73b

**Desktop (please complete the following information):**

- OS: W11
- Browser: Firefox
- Version: 121.0

**Comment by VampireChicken12** [comment]
@DesmoGiec are you sure you are using my extension and not another extension?

I tested this and the description of the shorts video appears perfectly fine for me.

**Comment by DesmoGiec** [comment]
Yeah, I'm using yours.
But, I've tried disabling other extensions, and the issue isn't there anymore.
Sorry for wasting your time, the issue was a conflict with another extension :)

**Comment by VampireChicken12** [comment]
@DesmoGiec it's fine
