### ISSUE TITLE
Feature menu doesn't work on a maximized player

### ISSUE THREAD

**Issue by rado84-github** [VampireChicken12/youtube-enhancer#220]
**Describe the bug**
When the player is maximized, the feature menu doesn't appear upon click.

**To Reproduce**

1. Set the extension to display a "maximize player" in the feature settings. Also set the feature menu to appear with a click (not on hover).
2. Maximize the player.
3. Click the feature menu and observe that nothing happens.

**Expected behavior**
The feature menu should appear even when the player is maximized.

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser: Firefox
- Version: YTE 1.19.1

**Comment by VampireChicken12** [comment]
@rado84-github thank you for making an issue. I'll look into the bug as soon as possible.

**Comment by VampireChicken12** [comment]
@rado84-github I fixed the issue. I'll reply when the new version is released. Since this issue relates to Maximize player feature I want to improve a few things related to it.

**Comment by VampireChicken12** [comment]
@rado84-github when version 1.19.2 is live on Mozilla Addons the issue will be fixed.

**Comment by VampireChicken12** [comment]
@allcontributors please add @rado84-github for bug

Version 1.19.2 is live on Mozilla addons

**Comment by rado84-github** [comment]
Wow, I didn't exect so quick reaction! :) Thanks for fixing it!

**Comment by VampireChicken12** [comment]
> Wow, I didn't exect so quick reaction! :) Thanks for fixing it!

No problem!

**Comment by VampireChicken12** [comment]
thanks for your review on Mozilla Addons @rado84-github

**Comment by rado84-github** [comment]
> thanks for your review on Mozilla Addons @rado84-github

I just saw my review didn't appear at all, so I edited it and now it does appear. Nothing but good impressions from me. ;)
