### ISSUE TITLE
[feature req.] Can you add a text field for CSS?

### ISSUE THREAD

**Issue by rado84-github** [VampireChicken12/youtube-enhancer#227]
Until two days ago I was using an extension for youtube which is no longer supported and was even removed from the firefox extensions website. But I had an older backup of my firefox where I extracted the extension from. That extension used to have a cool list of themes for YouTube that override the default black theme. So I found the theme's css file and I'd very much like to be able to use that theme with your extension but there's no CSS text field where to paste the code.

So, I'm requesting either a CSS text field where we could write custom CSS code
or
some kind of option to import CSS files.

If you prefer, I could give you both the whole outdated extension and all the themes it contains for you to add them to your extension?

**Comment by VampireChicken12** [comment]
@rado84-github I think I should be able to do that. If I used the CSS from the extension I would need to credit the original author if possible, If not possible I wouldn't use that CSS. At the very least I can add a custom CSS feature with an checkbox to enable it and a input box for adding the CSS you want to use.

**Comment by VampireChicken12** [comment]
I'm currently working on re-working the Maximize player feature it will work the same way but better. Right now it has a few flaws it has had them for a while.

**Comment by rado84-github** [comment]
> @rado84-github I think I should be able to do that. If I used the CSS from the extension I would need to credit the original author if possible, If not possible I wouldn't use that CSS. At the very least I can add a custom CSS feature with an checkbox to enable it and a input box for adding the CSS you want to use.

The original author's name is (I think) MRFDEV or something like that. Here's an archive with the entire xpi extension + a directory with the themes only. I think you should be able to find the full (nick)name of its developer, if you know where to look for it (cuz I don't).
https://disk.yandex.com/d/CrmON5qU8Advxg

It's on Yandex because they offered me a better plan for storage but in case you don't trust yandex for whatever reason, I can upload the archive on mediafire or 4shared.

**Comment by rado84-github** [comment]
I can't find a way to send you a message here, so I'll have to post here (again): I just sent you a friend request on Discord: Valso_BG.
