### ISSUE TITLE
Once activated, sound booster can't be deactivated

### ISSUE THREAD

**Issue by rado84-github** [VampireChicken12/youtube-enhancer#234]
**Describe the bug**
Once activated, sound booster can't be deactivated.

One of the videos I was watching had quite poor audio quality - too quiet, even when the slider was pushed to 100%, so I had to enable the booster. After I finished the video, I disabled the booster in the extension settings but that didn't change anything in general and all videos are now boosted which I can hear clearly since I'm using a 2.1 subwoofer system and when I increase the volume beyond 10%, distortions appear. Those distortions weren't there before I enabled the booster.

This means that once activated, the sound booster can't be deactivated, even if you disable it in the settings.

**To Reproduce**

1. Activate sound booster. Change any of the default settings, including decibels.
2. Run any video with the sound booster.
3. Then go back to the extension pop-up and deactivate the booster.
4. Run another video and listen for the sound - you'll see, or rather hear, that the sound levels haven't changed.

**Expected behavior**
Disabling the booster in the extension settings should return the sound levels to normal. "Normal" is anything without the extension or without the booster being enabled.

Screenshots aren't applicable, it's something you must hear, not see.

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser: Firefox 121.
- Version 1.19.4.

**Additional information**
I found a way to fix the problem for myself and bring the sound volume to the levels it was before even installing the extension.

Firefox --> about:config --> type "volume" in the search box --> change both "media" options to 0.1, restart the browser, change them back to 1.0 and restart the browser again.

**Comment by VampireChicken12** [comment]
@rado84-github let me investigate this
