### ISSUE TITLE
[Feature Request] Add support to remove yt shorts.

### ISSUE THREAD

**Issue by i2sage** [VampireChicken12/youtube-enhancer#240]
Removing Shorts from the homepage/feed,
Hiding Shorts from search results,
Remove Youtube Shorts Completely (like Enhancer and others).

**Comment by i2sage** [comment]
Question.
Do you use components from Revanced project or can it be used?

**Comment by VampireChicken12** [comment]
No the extension doesn't use anything from the revanced project

**Comment by VampireChicken12** [comment]
@i2sage I have done some research on how I can hide shorts content. I think I should be able to add a feature to hide them. Basically the same as removing but it allows users to enable the setting and disable and have the shorts content re-appear without having to reload the page.

**Comment by i2sage** [comment]
> @i2sage I have done some research on how I can hide shorts content. I think I should be able to add a feature to hide them. Basically the same as removing but it allows users to enable the setting and disable and have the shorts content re-appear without having to reload the page.
> 

Chris Titus made a video about that topic recently using unlock origin. Hope it gets implemented soon. Best of luck.

**Comment by VampireChicken12** [comment]
> > @i2sage I have done some research on how I can hide shorts content. I think I should be able to add a feature to hide them. Basically the same as removing but it allows users to enable the setting and disable and have the shorts content re-appear without having to reload the page.
> 
> Chris Titus made a video about that topic recently using unlock origin. Hope it gets implemented soon. Best of luck.

That is actually the video I got some info from. It should after I finish up the button placement feature. Thanks!

**Comment by i2sage** [comment]
Should I close this issue? or would you do it after you have implemented.

**Comment by VampireChicken12** [comment]
> Should I close this issue? or would you do it after you have implemented.

The issue will be closed automatically when I commit referencing this issue and that commit be included in a release.

**Comment by VampireChicken12** [comment]
![youtube-enhancer_-_youtube-enhancer_-_Spacetime_St_lMOVu5EwjT](https://github.com/VampireChicken12/youtube-enhancer/assets/45531575/de0d0269-d89c-4167-8ff8-f48e0b7264da)
Hard at work 😆

**Comment by VampireChicken12** [comment]
@i2sage sorry for not getting to this feature fast. I'm currently working on it. It's mostly done. Instead of removing the shorts the feature will hide them so if a user wants to disable the feature and be able to access shorts without reloading the page they can.

**Comment by VampireChicken12** [comment]
@i2sage 
Version 1.23.0 is live on [Mozilla Addons](https://addons.mozilla.org/en-US/firefox/addon/youtube-enhancer-vc/)
### Features
- **Hide Shorts:** Enhance your browsing experience by hiding distracting YouTube Shorts content.
- **Remove Redirect:** Save time with faster link navigation by removing unnecessary redirects.
- **Share Shortener:** Simplify shared URLs with our built-in shortener for cleaner and user-friendly links.
- **Shorts Auto Scroll:** Enjoy seamless viewing with automatic scrolling through YouTube Shorts.
