### ISSUE TITLE
Submit to Firefox Extension Store

### ISSUE THREAD

**Issue by slrgt** [VampireChicken12/youtube-enhancer#246]
**Is your feature request related to a problem? Please describe.**
It would be very useful to be able to get automatic updates of the extension by having it on the FireFox Extension Store.

**Describe the solution you'd like**
Please submit the extension to the official Firefox and Chrome extension stores

**Comment by VampireChicken12** [comment]
@slrgt the extension is on the Mozilla addons page.
 https://addons.mozilla.org/en-US/firefox/addon/youtube-enhancer-vc/

**Comment by VampireChicken12** [comment]
As for the chrome extension store I need to pay to make a developer account and at the moment I'm unable to. They only accept credit/debit card and I don't have one.
