### ISSUE TITLE
Program is Non-Functional on Firefox Floorp Browser

### ISSUE THREAD

**Issue by ShogoMechanics** [VampireChicken12/youtube-enhancer#256]
Program does not do anything while installed on Floorp
Tried restarting, resetting browser to default, removing all other addons, and the program options work, but nothing shows up on Youtube while active.

[Screenshot](https://i.imgur.com/E2AuUQj.png)

- OS: Windows 11
- Browser Floorp

**Comment by VampireChicken12** [comment]
@ShogoMechanics are you 100% sure you have the right extension? If you are I'll have to look into the issue.

**Comment by VampireChicken12** [comment]
Also if you are actually using my extension what version are you using.

**Comment by ShogoMechanics** [comment]
> Also if you are actually using my extension what version are you using.

I'm currently running the [1.20 version](https://i.imgur.com/oFTTQNs.png)

**Comment by VampireChicken12** [comment]
> > Also if you are actually using my extension what version are you using.
> 
> I'm currently running the [1.20.1 version](https://i.imgur.com/oFTTQNs.png)

Okay let me look into the issue.

**Comment by VampireChicken12** [comment]
@ShogoMechanics can you export your settings? I just did a fresh install of Floorp and the feature appear to be working fine
![Hopsin_-_Illmind_of_Hopsin_4_-_YouTube_—_Ablaze_Fl_K0ZaBkIeFa](https://github.com/VampireChicken12/youtube-enhancer/assets/45531575/7ed3812e-baa8-43b4-8b69-421274e0f285)

**Comment by ShogoMechanics** [comment]
Sorry for the delayed reply, I'm not entirely sure what I just did, but things seem to be working over here now!
