### ISSUE TITLE
not working on my firefox for unknown reasons

### ISSUE THREAD

**Issue by Ravord** [VampireChicken12/youtube-enhancer#360]
I believe I followed the instructions properly but only the extension menu seems to be working, there are no changes to youtube whatsoever
additionally: after restarting the browser, extension disappears

**Comment by VampireChicken12** [comment]
Can you send a video showing the extension settings then the extension not working

**Comment by VampireChicken12** [comment]
@Ravord 

> Can you send a video showing the extension settings then the extension not working

**Comment by Ravord** [comment]
okay so I was about to record a video but in the meanwhile I noticed that I was slightly mistaken as the extension was sometimes working and not working upon refreshing the page (most often it wasn't working)
but now that I'm thinking about it it's probably related to my issues with ublock origin and youtube slowing the loading of videopages for adblock users
anyway I kind of lost my interest in this extension so I'll be closing this issue and if I ever decide to return to it I'll try to fix my ublock problem first
