### ISSUE TITLE
[bug, I think] Automatic theatre mode - enabled/disabled are reversed

### ISSUE THREAD

**Issue by rado84-github** [VampireChicken12/youtube-enhancer#372]
**Describe the bug**
With "Automatic theatre mode - enabled" the player shrinks (shortens) and with "Automatic theatre mode - disabled" the player expands and takes the whole desktop length space which is the actual theatre mode.

**To Reproduce**

1. Load my settings:
[youtube_enhancer_settings_06.03.2024 г._16-19-06 ч..json.zip](https://github.com/VampireChicken12/youtube-enhancer/files/14511056/youtube_enhancer_settings_06.03.2024._16-19-06.json.zip)
2. Open any youtube video. It will load with a shortened player (meaning there's a panel on the right). Click to disable "Automatic theatre mode" and the player will expand to the maximum of the screen length. Then click to enable "Automatic theatre mode" and the player will shrink again.

**Expected behavior**
Automatic theatre mode - enabled" should expand the player to take the whole screen space, meaning that if your screen's native resolution is 1920x1080, then the expanded player should be 1920 pixels in length.

**Screenshots**
![automatic-theatre](https://github.com/VampireChicken12/youtube-enhancer/assets/41172201/251a068e-b817-4cbe-8f74-fdc3977053a0)

![disabled-automatic-theatre](https://github.com/VampireChicken12/youtube-enhancer/assets/41172201/2f6f377d-9039-436c-beab-b86b2269328f)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Firefox 123.0.1
- Version: 1.23.3

**Additional context**
I added "I think" in the title because it looks like a bug but I'm not 100% sure. Also, yesterday Firefox for Linux updated and this update MAY have something to do with this bug cuz Mozilla rarely announce the changes they make.
Also, I gave you my YTE settings, bc there's a remote chance something in my settings to cause the problem, though I personally doubt it.

Since yesterday I have a dual boot with Windows, so I'll try the same in Windows as well and then I'll report here whether the same is happening in Windows.

For the time being I've disabled "Automatic theatre mode" in order to have an expanded player.

**Comment by VampireChicken12** [comment]
Resolved
