### ISSUE TITLE
DeepDark custom CSS themes built in

### ISSUE THREAD

**Issue by VampireChicken12** [VampireChicken12/youtube-enhancer#381]
If granted permission by @RaitaroH this issue would add select options to apply deep dark themes without having to do it manually in the CSS editor.

**Comment by VampireChicken12** [comment]
I am hereby asking if it is okay to include the deep dark themes in my extension. Credit would be given if you allow it.

**Comment by RaitaroH** [comment]
Sure go ahead, given that you credit me.

**Comment by VampireChicken12** [comment]
> Sure go ahead, given that you credit me.

Thank you, will do.

**Comment by VampireChicken12** [comment]
![YouTube_Enhancer__Options_-_Google_Chrome_TflAqkFnrS](https://github.com/VampireChicken12/youtube-enhancer/assets/45531575/8ba3c1d2-280f-4386-99d2-52937bf7751d)
This is at the top of the CSS file
![deepDarkThemeTopOfCSS](https://github.com/VampireChicken12/youtube-enhancer/assets/45531575/2ebe0c45-12e0-44aa-bb68-63a5dde1c44a)
This is in the file where the theme variables are stored.
![deepDarkThemes](https://github.com/VampireChicken12/youtube-enhancer/assets/45531575/e8a7554c-db99-4102-b5e7-60f2b3ce6413)

@RaitaroH is this satisfactory for crediting?

**Comment by VampireChicken12** [comment]
If that doesn't work maybe this would
Youtube Deep Dark Settings
© RaitaroH, MechaLynx, MaximeRF

**Comment by VampireChicken12** [comment]
Let me know what works for you. I want to have this approved by you before it's released.

**Comment by VampireChicken12** [comment]
@RaitaroH I don't mean to bother you, but I want your input on how you want to be credited. I sent info above

**Comment by VampireChicken12** [comment]
I'm still working on the design but this is what it looks like right now. https://github.com/VampireChicken12/youtube-enhancer/assets/45531575/8a2b513d-1f9e-4d32-a2ee-f21e2a8569c2

**Comment by VampireChicken12** [comment]
The design has been finalized. I decided to use color pickers for the Custom theme variables.
![NVIDIA_GeForce_Overlay_DT_AGtjfbUyE4](https://github.com/VampireChicken12/youtube-enhancer/assets/45531575/39dc39fa-248a-4513-8e45-10cd368f8ebd)

**Comment by VampireChicken12** [comment]
@all-contributors
please add @RaitaroH for code
please add @MaximeRF for code
please add @MechaLynx for code

**Comment by VampireChicken12** [comment]
@all-contributors please add @MechaLynx for code

**Comment by MaximeRF** [comment]
@VampireChicken12 Please remove all references to me in your code and your repository as I don't want people to be confused and think that my extension is open source. You already chosen a similar name...

**Comment by VampireChicken12** [comment]
> @VampireChicken12 Please remove all references to me in your code and your repository as I don't want people to be confused and think that my extension is open source. You already chosen a similar name...

Alright will do

**Comment by RaitaroH** [comment]
@VampireChicken12 is ok.
